name: Parameterized Testing
on:
  pull_request:
    paths-ignore:
    - '**.md'
  push:
    paths-ignore:
    - '**.md'
  workflow_dispatch:
    inputs:
      testCategory:
        description: 'Test Category'
        required: true
        default: 'medium-tests'
      tags:
        description: 'Test scenario tags'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out source code
      uses: actions/checkout@v1

    - name: Install Java Development Kit 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build & Run small tests
      run: ./build.sh build

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: debug-apk
        path: uhabits-android/build/*apk

    - name: Upload build outputs
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: uhabits-android/build/outputs/

  test:
    needs: build
    runs-on: macOS-latest
    strategy:
      matrix:
        api-level: [28]
    steps:
    - name: Check out source code
      uses: actions/checkout@v1

    - name: Download previous build folder
      uses: actions/download-artifact@v2
      with:
        name: build
        path: uhabits-android/build/outputs/

    - name: Run tests
      uses: ReactiveCircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        script: ./build.sh ${{ github.event.inputs.testCategory }}
        arch: x86_64
